// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDR3M9xEoPS3DUhaQ0tBDxs1QzNbRGzWK8',
    appId: '1:51678365951:android:5f8c53174675e2cd3464ca',
    messagingSenderId: '51678365951',
    projectId: 'assisto-d824a',
    storageBucket: 'assisto-d824a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiEMe7DVN_TjuOEQFhcHV49Wp2gAwxZnw',
    appId: '1:51678365951:ios:e510716b617a43f93464ca',
    messagingSenderId: '51678365951',
    projectId: 'assisto-d824a',
    storageBucket: 'assisto-d824a.appspot.com',
    androidClientId: '51678365951-vkitcj71npa5b1nhh2kmel0dqoonl22b.apps.googleusercontent.com',
    iosClientId: '51678365951-bmntcuu861bcoekjavgur58ucg1611u5.apps.googleusercontent.com',
    iosBundleId: 'com.assisto.app',
  );
}
